//! Shared UI component library for the Flipper One 256x144 SPI panel.
//!
//! Three consumers: flipperos-installer (size-critical, maskrom-loaded),
//! flipper-boot-menu (Falcon initramfs) and flipctl (system launcher and UI
//! server for apps). Apps never link this crate; they talk to flipctl over
//! flipper-proto.

pub mod app;
pub mod boot;
pub mod font;
pub mod key;
pub mod keyboard;
pub mod layout;
pub mod net;
pub mod sysinfo;
pub mod watch;
pub mod platform;
pub mod status;
pub mod paint;
#[cfg(feature = "device")]
pub mod evdev;
#[cfg(feature = "device")]
pub mod kms;
#[cfg(feature = "remote")]
pub mod remote;
#[cfg(feature = "slint")]
pub mod slint_render;

/// The compiled .slint components.
///
/// Generated by slint-build from `ui/`, re-exported here so binaries do not each
/// have to run the compiler.
#[cfg(feature = "slint")]
pub mod ui {
    slint::include_modules!();
}
pub mod pixel;

/// Design tokens, generated from tokens.toml at build time.
#[allow(dead_code)]
pub mod theme {
    include!(concat!(env!("OUT_DIR"), "/theme.rs"));
}

pub use app::{AppEntry, RunningApp, Scene, SceneKind};
pub use font::BitmapFont;
pub use key::{FlipperKey, KeyEvent};
pub use platform::{Frame, FrameSink, InputSource};
pub use status::{Ethernet, Status, StatusSource};
pub use paint::Surface;
pub use pixel::{Gray8, Rect};
pub use theme::{PANEL_H, PANEL_W};
