//! Generates the Rust and Slint themes from tokens.toml.
//!
//! Both outputs come from one parse, so a rename cannot desync them. Nothing
//! outside the generated modules may hold a colour or a layout constant;
//! ci/no-raw-colours.sh enforces that.

use std::fmt::Write as _;
use std::{env, fs, path::PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=tokens.toml");

    let src = fs::read_to_string("tokens.toml").expect("tokens.toml");
    let doc: toml::Value = src.parse().expect("tokens.toml is not valid TOML");

    let out = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    write_if_changed(&out.join("theme.rs"), &rust_theme(&doc));
    let theme_slint = out.join("theme.slint");
    write_if_changed(&theme_slint, &slint_theme(&doc));

    #[cfg(feature = "slint")]
    compile_slint(&theme_slint);
}

/// Write `contents` to `path` only if they differ from what is already there.
///
/// This is not an optimisation, it is what makes incremental builds work at all.
/// `theme.slint` is generated here and then read by the Slint compiler, which
/// declares it as a build input, so its mtime is part of this script's
/// fingerprint. Rewriting it unconditionally stamps it after the timestamp cargo
/// records for the script's own completion, which cargo reads as "an input
/// changed" and reruns the script on the next build, forever. On the Flipper that
/// cost a full 83-second recompile of both crates on every single build, even with
/// nothing touched:
///
///     stale: out/theme.slint (vs) out/output
///     FileTime { seconds: .., nanos: 377030560 } < FileTime { .., nanos: 397030653 }
///
/// Leaving an unchanged file alone keeps its mtime older than that marker and the
/// loop cannot start. The host happened not to trip it, which is why this survived
/// as long as it did.
fn write_if_changed(path: &std::path::Path, contents: &str) {
    if fs::read_to_string(path).is_ok_and(|old| old == contents) {
        return;
    }
    fs::write(path, contents).unwrap_or_else(|e| panic!("write {}: {e}", path.display()));
}

/// Compile the .slint components against the generated theme.
///
/// `EmbedForSoftwareRenderer` pre-rasterises the glyphs at compile time, which
/// is what lets the runtime drop the font engine (and with it fontique's
/// fontconfig enumeration, the reason the installer currently ships TTFs into
/// /usr/share/fonts just to avoid a startup panic).
///
/// SLINT_FONT_SIZES is pinned to 16 and must stay there: the FlipCTL fonts are
/// pixel fonts on a 64-unit design-pixel grid at 1024 units/em, so they
/// rasterise with zero partial coverage at 16px and antialias at anything else.
#[cfg(feature = "slint")]
fn compile_slint(theme: &std::path::Path) {
    println!("cargo:rerun-if-changed=ui");

    std::env::set_var("SLINT_FONT_SIZES", "16");

    let mut libs = std::collections::HashMap::new();
    libs.insert("theme".to_string(), theme.to_path_buf());

    let config = slint_build::CompilerConfiguration::new()
        .embed_resources(slint_build::EmbedResourcesKind::EmbedForSoftwareRenderer)
        .with_library_paths(libs);

    slint_build::compile_with_config("ui/screens.slint", config)
        .expect("compile ui/screens.slint");
}

fn table<'a>(doc: &'a toml::Value, key: &str) -> &'a toml::value::Table {
    doc.get(key)
        .unwrap_or_else(|| panic!("tokens.toml has no [{key}] table"))
        .as_table()
        .unwrap_or_else(|| panic!("[{key}] is not a table"))
}

fn parse_hex(name: &str, hex: &str) -> (u8, u8, u8) {
    let body = hex.strip_prefix('#').unwrap_or_else(|| {
        panic!("colour `{name}` = {hex:?} must start with #");
    });
    if body.len() != 6 {
        panic!("colour `{name}` = {hex:?} must be #rrggbb, six digits, no shorthand");
    }
    let byte = |i: usize| {
        u8::from_str_radix(&body[i..i + 2], 16)
            .unwrap_or_else(|_| panic!("colour `{name}` = {hex:?} is not hex"))
    };
    (byte(0), byte(2), byte(4))
}

fn ints(doc: &toml::Value, key: &str) -> Vec<(String, i64)> {
    let mut v: Vec<(String, i64)> = table(doc, key)
        .iter()
        .map(|(k, val)| {
            let n = val
                .as_integer()
                .unwrap_or_else(|| panic!("[{key}].{k} must be an integer pixel count"));
            (k.clone(), n)
        })
        .collect();
    v.sort();
    v
}

fn colors(doc: &toml::Value) -> Vec<(String, String, (u8, u8, u8))> {
    let mut v: Vec<_> = table(doc, "color")
        .iter()
        .map(|(k, val)| {
            let hex = val
                .as_str()
                .unwrap_or_else(|| panic!("[color].{k} must be a #rrggbb string"))
                .to_string();
            let rgb = parse_hex(k, &hex);
            (k.clone(), hex, rgb)
        })
        .collect();
    v.sort();
    v
}

fn rust_theme(doc: &toml::Value) -> String {
    let mut s = String::from(
        "// @generated by build.rs from tokens.toml. Do not edit.\n\n\
         use crate::pixel::Gray8;\n\n",
    );

    let cols = colors(doc);

    s.push_str("/// Every colour token. The panel is 8-bit greyscale, so a token is a single\n\
                /// grey level; the r/g/b triple is kept for the Slint side and the tests.\n\
                pub mod color {\n    use super::Gray8;\n\n");
    for (name, hex, (r, g, b)) in &cols {
        writeln!(s, "    /// `{hex}`").unwrap();
        writeln!(
            s,
            "    pub const {}: Gray8 = Gray8({r});",
            name.to_uppercase()
        )
        .unwrap();
        let _ = (g, b);
    }
    s.push_str("}\n\n");

    s.push_str("/// (name, hex, r, g, b) for every colour token, for the invariant tests.\n");
    writeln!(
        s,
        "pub const ALL_COLORS: [(&str, &str, u8, u8, u8); {}] = [",
        cols.len()
    )
    .unwrap();
    for (name, hex, (r, g, b)) in &cols {
        writeln!(s, "    ({name:?}, {hex:?}, {r}, {g}, {b}),").unwrap();
    }
    s.push_str("];\n\n");

    for group in ["metric", "radius", "timing", "count"] {
        let items = ints(doc, group);
        writeln!(s, "pub mod {group} {{").unwrap();
        for (name, n) in &items {
            writeln!(s, "    pub const {}: i32 = {n};", name.to_uppercase()).unwrap();
        }
        s.push_str("}\n\n");
        writeln!(
            s,
            "pub const ALL_{}: [(&str, i32); {}] = [",
            group.to_uppercase(),
            items.len()
        )
        .unwrap();
        for (name, n) in &items {
            writeln!(s, "    ({name:?}, {n}),").unwrap();
        }
        s.push_str("];\n\n");
    }

    let alpha = table(doc, "alpha");
    s.push_str("pub mod alpha {\n");
    let mut akeys: Vec<_> = alpha.iter().collect();
    akeys.sort_by_key(|(k, _)| (*k).clone());
    for (name, val) in &akeys {
        let f = val
            .as_float()
            .unwrap_or_else(|| panic!("[alpha].{name} must be a float"));
        writeln!(s, "    pub const {}: f32 = {f};", name.to_uppercase()).unwrap();
    }
    s.push_str("}\n\n");

    let rules = table(doc, "rule");
    let mut rkeys: Vec<_> = rules.iter().collect();
    rkeys.sort_by_key(|(k, _)| (*k).clone());
    s.push_str("/// System-wide rules, decided once in tokens.toml.\npub mod rule {\n");
    for (name, val) in &rkeys {
        let v = val
            .as_str()
            .unwrap_or_else(|| panic!("[rule].{name} must be a string"));
        writeln!(s, "    pub const {}: &str = {v:?};", name.to_uppercase()).unwrap();
    }
    s.push_str("}\n\n");

    let meta = table(doc, "meta");
    let w = meta["panel_width"].as_integer().unwrap();
    let h = meta["panel_height"].as_integer().unwrap();
    writeln!(s, "pub const PANEL_W: u16 = {w};").unwrap();
    writeln!(s, "pub const PANEL_H: u16 = {h};").unwrap();
    s.push('\n');

    let fonts = table(doc, "font");
    let mut fkeys: Vec<_> = fonts.iter().collect();
    fkeys.sort_by_key(|(k, _)| (*k).clone());
    s.push_str("/// Font frame geometry. Advance width is per-glyph and lives in the glyph\n\
                /// tables, so text width is a sum and never a multiplication.\n\
                pub mod font {\n    pub struct FontMetrics {\n        \
                pub name: &'static str,\n        pub rows: u8,\n        pub cols: u8,\n    }\n\n");
    for (key, val) in &fkeys {
        let t = val.as_table().unwrap();
        let name = t["name"].as_str().unwrap();
        let rows = t["rows"].as_integer().unwrap();
        let cols = t["cols"].as_integer().unwrap();
        writeln!(
            s,
            "    pub const {}: FontMetrics = FontMetrics {{ name: {name:?}, rows: {rows}, cols: {cols} }};",
            key.to_uppercase()
        )
        .unwrap();
    }
    s.push_str("}\n");

    s
}

fn slint_theme(doc: &toml::Value) -> String {
    let mut s = String::from("// @generated by build.rs from tokens.toml. Do not edit.\n\nexport global FlipperTheme {\n");

    for (name, hex, _) in colors(doc) {
        writeln!(s, "    out property <color> {name}: {hex};").unwrap();
    }
    for group in ["metric", "radius"] {
        for (name, n) in ints(doc, group) {
            writeln!(s, "    out property <length> {name}: {n}px;").unwrap();
        }
    }
    // Counts are plain integers: Slint refuses to compare or multiply a length
    // with one, which is exactly the mistake this separation prevents.
    for (name, n) in ints(doc, "count") {
        writeln!(s, "    out property <int> {name}: {n};").unwrap();
    }
    for (name, n) in ints(doc, "timing") {
        writeln!(s, "    out property <duration> {name}: {n}ms;").unwrap();
    }
    let alpha = table(doc, "alpha");
    let mut akeys: Vec<_> = alpha.iter().collect();
    akeys.sort_by_key(|(k, _)| (*k).clone());
    for (name, val) in akeys {
        writeln!(
            s,
            "    out property <float> {name}_alpha: {};",
            val.as_float().unwrap()
        )
        .unwrap();
    }
    let rules = table(doc, "rule");
    let mut rkeys: Vec<_> = rules.iter().collect();
    rkeys.sort_by_key(|(k, _)| (*k).clone());
    for (name, val) in rkeys {
        writeln!(
            s,
            "    out property <string> {name}_rule: {:?};",
            val.as_str().unwrap()
        )
        .unwrap();
    }
    s.push_str("}\n");
    s
}
