#!/usr/bin/env python3
"""Convert a fake-flipctl2 bitmap font module into a Rust glyph table.

The prototype's fonts are already packed 1bpp tables generated from the
flipctl-fonts TTFs by ttf-to-js.py: ROWS rows of COLS bits per glyph, MSB is
the leftmost pixel, plus a per-glyph advance width. Reusing the tables verbatim
is the only way to get output that is pixel-identical to the reviewed prototype;
re-rasterising the TTFs would reintroduce antialiasing the design explicitly
rules out.

Usage: js-font-to-rust.py <font.js> <RustName> > out.rs
"""
import re
import sys

FIRST, LAST = 32, 126


def parse(path):
    src = open(path, encoding="utf-8").read()

    cols = int(re.search(r"var COLS = (\d+);", src).group(1))
    rows = int(re.search(r"var ROWS = (\d+);", src).group(1))

    glyphs = {}
    for m in re.finditer(r"(\d+):\s*\{r:\[([^\]]*)\],\s*a:\s*(\d+)\}", src):
        code = int(m.group(1))
        bits = [int(v) for v in m.group(2).split(",")]
        advance = int(m.group(3))
        if len(bits) != rows:
            raise SystemExit(f"{path}: glyph {code} has {len(bits)} rows, expected {rows}")
        if max(bits) >= 1 << cols:
            raise SystemExit(f"{path}: glyph {code} has a row wider than {cols} bits")
        glyphs[code] = (advance, bits)

    missing = [c for c in range(FIRST, LAST + 1) if c not in glyphs]
    if missing:
        raise SystemExit(f"{path}: missing glyphs for {missing}")
    return rows, cols, glyphs


def screaming_snake(camel):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", camel).upper()


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    path, name = sys.argv[1], sys.argv[2]
    const = screaming_snake(name)
    rows, cols, glyphs = parse(path)

    out = [
        f"// @generated by tools/js-font-to-rust.py from {path.split('/')[-1]}. Do not edit.",
        "",
        f"/// {name}: {rows} rows of {cols} bits, MSB is the leftmost pixel.",
        f"pub const {const}: BitmapFont = BitmapFont {{",
        f"    rows: {rows},",
        f"    cols: {cols},",
        f"    first: {FIRST},",
        f"    glyphs: &{const}_GLYPHS,",
        "};",
        "",
        f"const {const}_GLYPHS: [Glyph; {LAST - FIRST + 1}] = [",
    ]
    for code in range(FIRST, LAST + 1):
        advance, bits = glyphs[code]
        ch = chr(code)
        label = "space" if ch == " " else ch.replace("\\", "\\\\").replace("'", "\\'")
        packed = ", ".join(f"0x{b:04x}" for b in bits)
        out.append(f"    // {code} {label}")
        out.append(f"    Glyph {{ advance: {advance}, rows: &[{packed}] }},")
    out.append("];")
    out.append("")
    print("\n".join(out))


if __name__ == "__main__":
    main()
